### ISSUE TITLE
I can't keep up with gettest on the mentioned webserver!

### ISSUE THREAD

**Issue by john-solen** [lnxpy/codehub#1]
Hey Ali,
Hope you doing well.

I have already forked codehub and also pushed up on the pythonanywhere webserver. I can't localize my website using gettest. do you have any idea? 
Does it for u?

**Comment by lnxpy** [comment]
Hey John,
Thanks.

Unfortunately pythonanywhere does not let you to install external packages on the installed distribution so you need to find something else. I also have this issue. It works find on my local system. I found several packages in pip you may get the result. Google for `gettext-python` package.

I also prefer you to use VPS instead of pythonanywhere.
Hope It works.

**Comment by john-solen** [comment]
I wanna use VPS too.
I just changed it to En language and made some changes on views and so on. It's amazing.

Thanks bro.
