### ISSUE TITLE
داداش چرا ترجمه هات کار نمیکنن؟

### ISSUE THREAD

**Issue by ashkan1375** [lnxpy/codehub#2]
سلام علی جان
منم مثل خودت روی سرور های پایتون انی ور پروژه رو ریختم اما نمیدونم چرا ترجمه هات کار نمیکنن.
یه دوست هم مثل اینکه به این مشکل خورده بود و ایشوش بسته شده وگرنه اونجا میگفتم.

دستت درد نکنه عشقی استاد. کاراتو گیت هاب میبینم خیلی جذابن

**Comment by lnxpy** [comment]
Hey Ashkan,

When you `makemessages` your compiled file (.mo) will be ignored on deployment side. You need to recompile your `.po` file to create a new compile file. You won't need to translate again your new words because you have already translated them on your local system. 

It worked for me. Hope works for you too. :smiley:
Thanks bro. It's your kindness. :heart:

**Comment by ashkan1375** [comment]
مرسی خیلی لطف کردی. خیلی باهاش کلنجار رفتم و خوشبختانه درست شد. دستت درد نکنه. ولی چجوری makemessages رو انجام بدم؟

منظورم اینه که چجوری بنویسمش؟

**Comment by lnxpy** [comment]
```bash
django-admin makemessages -l <your-language (e.g fa)>
```
